#!/usr/bin/env bun
import { readdirSync, existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";

// ponytail: repo path, not import.meta.dir — the compiled binary outlives its
// build directory but still needs to read themes/ at runtime.
export const RICE_HOME = process.env.RICE_HOME ?? join(homedir(), "cc", "rice");
const THEMES = join(RICE_HOME, "themes");

export type Theme = {
  slug: string;
  dir: string;
  meta: { name: string; variant: "dark" | "light"; description: string };
  roles: Record<Role, string>;
  extras: Record<string, string>;
  ansi: Record<AnsiName, [string, string]>;
  render: { opacity: number };
};

export type Role =
  | "base" | "surface" | "overlay" | "text" | "muted" | "accent" | "deep" | "on_fill";
export type AnsiName =
  | "black" | "red" | "green" | "yellow" | "blue" | "magenta" | "cyan" | "white";

const ROLES: Role[] = ["base", "surface", "overlay", "text", "muted", "accent", "deep", "on_fill"];
const ANSI: AnsiName[] = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"];

/** Parse and validate a palette. Throws with a human message on any problem. */
export function parseTheme(slug: string, dir: string, raw: string): Theme {
  // ponytail: substring check, not a recursive walk. A TODO anywhere in the
  // file — value or comment — means the palette is not finished.
  if (raw.includes("TODO")) throw new Error(`${slug}: palette has TODOs, finish it before applying`);

  const t = Bun.TOML.parse(raw) as any;
  if (t?.meta?.variant !== "dark" && t?.meta?.variant !== "light")
    throw new Error(`${slug}: meta.variant must be "dark" or "light"`);
  if (!t?.meta?.name) throw new Error(`${slug}: meta.name is required`);

  for (const r of ROLES) {
    if (!isHex(t?.roles?.[r])) throw new Error(`${slug}: roles.${r} missing or not #rrggbb`);
  }
  for (const a of ANSI) {
    const pair = t?.ansi?.[a];
    if (!Array.isArray(pair) || pair.length !== 2 || !pair.every(isHex))
      throw new Error(`${slug}: ansi.${a} must be [normal, bright] hex pair`);
  }

  return {
    slug,
    dir,
    meta: t.meta,
    roles: t.roles,
    extras: t.extras ?? {},
    ansi: t.ansi,
    render: { opacity: t.render?.opacity ?? (t.meta.variant === "dark" ? 0.92 : 1) },
  };
}

export function isHex(v: unknown): v is string {
  return typeof v === "string" && /^#[0-9a-fA-F]{6}$/.test(v);
}

export function loadTheme(slug: string): Theme {
  const dir = join(THEMES, slug);
  const file = join(dir, "palette.toml");
  if (!existsSync(file)) throw new Error(`no theme "${slug}" — try: rice list`);
  return parseTheme(slug, dir, readFileSync(file, "utf8"));
}

export function listThemes(): string[] {
  if (!existsSync(THEMES)) return [];
  return readdirSync(THEMES, { withFileTypes: true })
    .filter((e) => e.isDirectory() && existsSync(join(THEMES, e.name, "palette.toml")))
    .map((e) => e.name)
    .sort();
}

// ── surfaces ────────────────────────────────────────────────────────────────
// A surface returns its name when it applied the theme, or null when the app
// isn't set up on this machine. Nothing here rewrites a whole config: rice
// owns theme files plus one pointer line, dovetail owns the rest.

const CONFIG = join(homedir(), ".config");

type Surface = { name: string; apply: (t: Theme) => string | null };

/** Swap the one line matching `re`. Hard-fails unless the match count is exactly 1. */
export function replaceLine(text: string, re: RegExp, line: string): string {
  const found = text.match(new RegExp(re.source, "gm"));
  if (found?.length !== 1)
    throw new Error(`expected 1 line matching ${re.source}, found ${found?.length ?? 0}`);
  // ponytail: function replacement so $& and friends in `line` stay literal.
  return text.replace(new RegExp(re.source, "m"), () => line);
}

/**
 * Replace whatever sits between `<comment> rice:start` and `<comment> rice:end`.
 * Body lines inherit the start marker's indentation, which YAML needs and the
 * bash arrays look better for.
 */
export function inject(text: string, body: string, comment = "#"): string {
  const START = `${comment} rice:start`;
  const END = `${comment} rice:end`;
  const i = text.indexOf(START);
  const j = text.indexOf(END);
  if (i === -1 || j === -1 || j < i) throw new Error(`missing "${START}" / "${END}" markers`);
  const indent = text.slice(text.lastIndexOf("\n", i) + 1, i);
  const lines = body.split("\n").map((l) => (l ? indent + l : l)).join("\n");
  return `${text.slice(0, i)}${START}\n${lines}\n${indent}${text.slice(j)}`;
}

const bare = (hex: string) => hex.slice(1);

/** 0xAARRGGBB — what borders and sketchybar want. */
export const argb = (hex: string, alpha = "ff") => `0x${alpha}${bare(hex)}`;

/** A ghostty theme file: everything except `theme` and `config-file` is allowed. */
export function ghosttyTheme(t: Theme): string {
  return [
    `# ${t.meta.name} — generated by rice, do not edit`,
    `background = ${bare(t.roles.base)}`,
    `foreground = ${bare(t.roles.text)}`,
    `cursor-color = ${bare(t.roles.accent)}`,
    `cursor-text = ${bare(t.roles.on_fill)}`,
    `selection-background = ${bare(t.roles.overlay)}`,
    `selection-foreground = ${bare(t.ansi.white[1])}`,
    `background-opacity = ${t.render.opacity}`,
    ...ANSI.map((n, i) => `palette = ${i}=${t.ansi[n][0]}`),
    ...ANSI.map((n, i) => `palette = ${i + 8}=${t.ansi[n][1]}`),
    "",
  ].join("\n");
}

/** A btop `.theme` file. Gradients run cool → accent so load reads as heat. */
export function btopTheme(t: Theme): string {
  const r = t.roles, a = t.ansi;
  const pairs: [string, string][] = [
    ["main_bg", r.base], ["main_fg", r.text], ["title", r.text],
    ["hi_fg", r.accent], ["selected_bg", r.overlay], ["selected_fg", r.accent],
    ["inactive_fg", r.muted], ["graph_text", r.text], ["meter_bg", a.black[0]],
    ["proc_misc", a.yellow[0]],
    ["cpu_box", r.muted], ["mem_box", r.muted], ["net_box", r.muted],
    ["proc_box", r.muted], ["div_line", a.black[0]],
    ["cpu_start", a.blue[0]], ["cpu_mid", a.blue[1]], ["cpu_end", r.accent],
    ["temp_start", a.green[0]], ["temp_mid", a.yellow[0]], ["temp_end", a.red[0]],
    ["free_start", r.overlay], ["free_mid", a.blue[0]], ["free_end", a.blue[1]],
    ["cached_start", a.cyan[0]], ["cached_mid", a.cyan[1]], ["cached_end", a.green[1]],
    ["available_start", a.green[0]], ["available_mid", a.green[1]], ["available_end", a.yellow[0]],
    ["used_start", r.deep], ["used_mid", a.red[0]], ["used_end", r.accent],
    ["download_start", a.blue[0]], ["download_mid", a.blue[1]], ["download_end", a.cyan[1]],
    ["upload_start", r.deep], ["upload_mid", a.magenta[0]], ["upload_end", r.accent],
    ["process_start", a.blue[0]], ["process_mid", a.magenta[0]], ["process_end", r.accent],
  ];
  return [
    `# ${t.meta.name} — generated by rice, do not edit`,
    ...pairs.map(([k, v]) => `theme[${k}]="${v}"`),
    "",
  ].join("\n");
}

/** The exported shell vars sketchybarrc and its plugins read. */
export function sketchybarColors(t: Theme): string {
  const r = t.roles;
  return [
    `export BASE=${argb(r.base)}`,
    `export BAR_BG=0x00000000`, // pills float on the wallpaper, no backdrop
    `export SURFACE=${argb(r.surface)}`,
    `export OVERLAY=${argb(r.overlay)}`,
    `export TEXT=${argb(r.text)}`,
    `export MUTED=${argb(r.muted)}`,
    `export ACCENT=${argb(r.accent)}`,
    `export DEEP=${argb(r.deep)}`,
    `export RED=${argb(t.ansi.red[0])}`,
    `export ON_FILL=${argb(r.on_fill)}`,
    `export TRANSPARENT=0x00000000`,
  ].join("\n");
}

/** A yazi flavor. theme.toml keeps only the [flavor] pointer; this holds the colors. */
export function yaziFlavor(t: Theme): string {
  const r = t.roles, a = t.ansi;
  return `# ${t.meta.name} — generated by rice, do not edit

[mgr]
cwd = { fg = "${a.cyan[1]}" }

hovered         = { fg = "${r.on_fill}", bg = "${r.accent}" }
preview_hovered = { underline = true }

find_keyword  = { fg = "${r.accent}", italic = true }
find_position = { fg = "${a.magenta[0]}", bg = "reset", italic = true }

marker_copied   = { fg = "${a.green[0]}", bg = "${a.green[0]}" }
marker_cut      = { fg = "${a.red[0]}", bg = "${a.red[0]}" }
marker_marked   = { fg = "${a.cyan[0]}", bg = "${a.cyan[0]}" }
marker_selected = { fg = "${r.accent}", bg = "${r.accent}" }

count_copied   = { fg = "${r.on_fill}", bg = "${a.green[0]}" }
count_cut      = { fg = "${r.on_fill}", bg = "${a.red[0]}" }
count_selected = { fg = "${r.on_fill}", bg = "${r.accent}" }

border_symbol = "│"
border_style  = { fg = "${r.overlay}" }

[mode]
normal_main = { fg = "${r.on_fill}", bg = "${r.accent}", bold = true }
normal_alt  = { fg = "${r.accent}", bg = "${r.surface}" }
select_main = { fg = "${r.on_fill}", bg = "${a.green[0]}", bold = true }
select_alt  = { fg = "${a.green[0]}", bg = "${r.surface}" }
unset_main  = { fg = "${r.on_fill}", bg = "${a.magenta[0]}", bold = true }
unset_alt   = { fg = "${a.magenta[0]}", bg = "${r.surface}" }

[status]
perm_type  = { fg = "${a.cyan[0]}" }
perm_read  = { fg = "${a.yellow[0]}" }
perm_write = { fg = "${a.red[0]}" }
perm_exec  = { fg = "${a.green[0]}" }
perm_sep   = { fg = "${r.muted}" }
progress_label  = { fg = "${r.text}", bold = true }
progress_normal = { fg = "${r.accent}", bg = "${r.surface}" }
progress_error  = { fg = "${a.red[0]}", bg = "${r.surface}" }

[pick]
border   = { fg = "${r.accent}" }
active   = { fg = "${r.accent}", bold = true }
inactive = { fg = "${r.text}" }

[input]
border   = { fg = "${r.accent}" }
selected = { reversed = true }

[cmp]
border   = { fg = "${r.accent}" }
active   = { fg = "${r.accent}", bold = true }
inactive = { fg = "${r.text}" }

[tasks]
border  = { fg = "${r.accent}" }
hovered = { fg = "${r.accent}", underline = true }

[which]
mask            = { bg = "${r.surface}" }
cand            = { fg = "${a.cyan[1]}" }
rest            = { fg = "${r.muted}" }
desc            = { fg = "${r.accent}" }
separator       = "  "
separator_style = { fg = "${r.overlay}" }

[help]
on      = { fg = "${r.accent}" }
run     = { fg = "${a.cyan[1]}" }
hovered = { reversed = true, bold = true }
footer  = { fg = "${r.surface}", bg = "${r.text}" }

[notify]
title_info  = { fg = "${a.green[0]}" }
title_warn  = { fg = "${a.yellow[0]}" }
title_error = { fg = "${a.red[0]}" }

[filetype]
rules = [
  { mime = "image/*", fg = "${a.cyan[1]}" },
  { mime = "video/*", fg = "${a.yellow[0]}" },
  { mime = "audio/*", fg = "${a.yellow[0]}" },
  { mime = "application/zip",  fg = "${a.magenta[0]}" },
  { mime = "application/gzip", fg = "${a.magenta[0]}" },
  { url = "*/", fg = "${a.blue[1]}" },
  { url = "*",  fg = "${r.text}" },
]
`;
}

export const SURFACES: Surface[] = [
  {
    name: "ghostty",
    apply(t) {
      const dir = join(CONFIG, "ghostty");
      const cfg = join(dir, "config");
      if (!existsSync(cfg)) return null;
      mkdirSync(join(dir, "themes"), { recursive: true });
      writeFileSync(join(dir, "themes", t.slug), ghosttyTheme(t));
      writeFileSync(
        cfg,
        replaceLine(readFileSync(cfg, "utf8"), /^theme = .*$/, `theme = ${t.slug}`),
      );
      return "ghostty (supacode reads this config; p10k + fastfetch inherit its ANSI)";
    },
  },
  {
    name: "btop",
    apply(t) {
      const dir = join(CONFIG, "btop");
      const cfg = join(dir, "btop.conf");
      if (!existsSync(cfg)) return null;
      mkdirSync(join(dir, "themes"), { recursive: true });
      writeFileSync(join(dir, "themes", `${t.slug}.theme`), btopTheme(t));
      writeFileSync(
        cfg,
        replaceLine(readFileSync(cfg, "utf8"), /^color_theme = .*$/, `color_theme = "${t.slug}"`),
      );
      return "btop";
    },
  },
  {
    name: "borders",
    apply(t) {
      const rc = join(CONFIG, "borders", "bordersrc");
      if (!existsSync(rc)) return null;
      const body = [
        `active_color=${argb(t.roles.accent)}`,
        `inactive_color=${argb(t.ansi.black[0])}`,
      ].join("\n");
      writeFileSync(rc, inject(readFileSync(rc, "utf8"), body));
      return "borders (reload: brew services restart borders)";
    },
  },
  {
    name: "wallpaper",
    apply(t) {
      const file = readdirSync(t.dir).find((f) => f.startsWith("wallpaper."));
      if (!file) return null;
      // ponytail: JSON.stringify quotes the path well enough for AppleScript;
      // theme dirs are slugs, so no quotes or backslashes to escape.
      const script = `tell application "System Events" to set picture of every desktop to ${JSON.stringify(join(t.dir, file))}`;
      const r = Bun.spawnSync(["osascript", "-e", script]);
      if (r.exitCode !== 0) throw new Error(`wallpaper: ${r.stderr.toString().trim()}`);
      return `wallpaper (${file})`;
    },
  },
  {
    name: "sketchybar",
    apply(t) {
      const f = join(CONFIG, "sketchybar", "colors.sh");
      if (!existsSync(f)) return null;
      writeFileSync(f, inject(readFileSync(f, "utf8"), sketchybarColors(t)));
      Bun.spawnSync(["sketchybar", "--reload"]);
      return "sketchybar";
    },
  },
  {
    name: "yazi",
    apply(t) {
      const dir = join(CONFIG, "yazi");
      const theme = join(dir, "theme.toml");
      if (!existsSync(theme)) return null;
      const flavor = join(dir, "flavors", `${t.slug}.yazi`);
      mkdirSync(flavor, { recursive: true });
      writeFileSync(join(flavor, "flavor.toml"), yaziFlavor(t));
      const key = t.meta.variant === "dark" ? "dark" : "light";
      writeFileSync(
        theme,
        replaceLine(readFileSync(theme, "utf8"), new RegExp(`^${key} = .*$`), `${key} = "${t.slug}"`),
      );
      return "yazi";
    },
  },
];

const HELP = `rice — switch the whole desktop to a theme

usage:
  rice list              show available themes
  rice use <theme>       apply a theme to every surface
  rice -h, --help        this
`;

function main() {
  const [cmd, arg] = process.argv.slice(2);

  if (!cmd || cmd === "-h" || cmd === "--help") return console.log(HELP);

  if (cmd === "list") {
    for (const slug of listThemes()) {
      const t = loadTheme(slug);
      console.log(`${slug.padEnd(16)} ${t.meta.name} (${t.meta.variant}) — ${t.meta.description}`);
    }
    return;
  }

  if (cmd === "use") {
    if (!arg) throw new Error("usage: rice use <theme>");
    const t = loadTheme(arg);
    console.log(t.meta.name);
    for (const s of SURFACES) {
      const done = s.apply(t);
      console.log(done ? `  ✓ ${done}` : `  · ${s.name} not set up here, skipped`);
    }
    return;
  }

  throw new Error(`unknown command "${cmd}"\n\n${HELP}`);
}

if (import.meta.main) {
  try {
    main();
  } catch (e) {
    console.error(`rice: ${(e as Error).message}`);
    process.exit(1);
  }
}
