#!/usr/bin/env bun
import { readdirSync, existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";

// ponytail: repo path, not import.meta.dir — the compiled binary outlives its
// build directory but still needs to read themes/ at runtime.
export const RICE_HOME = process.env.RICE_HOME ?? join(homedir(), "cc", "rice");
const THEMES = join(RICE_HOME, "themes");

export type Theme = {
  slug: string;
  dir: string;
  meta: { name: string; variant: "dark" | "light"; description: string };
  roles: Record<Role, string>;
  extras: Record<string, string>;
  ansi: Record<AnsiName, [string, string]>;
  render: { opacity: number };
};

export type Role =
  | "base" | "surface" | "overlay" | "text" | "muted" | "accent" | "deep" | "on_fill";
export type AnsiName =
  | "black" | "red" | "green" | "yellow" | "blue" | "magenta" | "cyan" | "white";

const ROLES: Role[] = ["base", "surface", "overlay", "text", "muted", "accent", "deep", "on_fill"];
const ANSI: AnsiName[] = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"];

/** Parse and validate a palette. Throws with a human message on any problem. */
export function parseTheme(slug: string, dir: string, raw: string): Theme {
  // ponytail: substring check, not a recursive walk. A TODO anywhere in the
  // file — value or comment — means the palette is not finished.
  if (raw.includes("TODO")) throw new Error(`${slug}: palette has TODOs, finish it before applying`);

  const t = Bun.TOML.parse(raw) as any;
  if (t?.meta?.variant !== "dark" && t?.meta?.variant !== "light")
    throw new Error(`${slug}: meta.variant must be "dark" or "light"`);
  if (!t?.meta?.name) throw new Error(`${slug}: meta.name is required`);

  for (const r of ROLES) {
    if (!isHex(t?.roles?.[r])) throw new Error(`${slug}: roles.${r} missing or not #rrggbb`);
  }
  for (const a of ANSI) {
    const pair = t?.ansi?.[a];
    if (!Array.isArray(pair) || pair.length !== 2 || !pair.every(isHex))
      throw new Error(`${slug}: ansi.${a} must be [normal, bright] hex pair`);
  }

  return {
    slug,
    dir,
    meta: t.meta,
    roles: t.roles,
    extras: t.extras ?? {},
    ansi: t.ansi,
    render: { opacity: t.render?.opacity ?? (t.meta.variant === "dark" ? 0.92 : 1) },
  };
}

export function isHex(v: unknown): v is string {
  return typeof v === "string" && /^#[0-9a-fA-F]{6}$/.test(v);
}

export function loadTheme(slug: string): Theme {
  const dir = join(THEMES, slug);
  const file = join(dir, "palette.toml");
  if (!existsSync(file)) throw new Error(`no theme "${slug}" — try: rice list`);
  return parseTheme(slug, dir, readFileSync(file, "utf8"));
}

export function listThemes(): string[] {
  if (!existsSync(THEMES)) return [];
  return readdirSync(THEMES, { withFileTypes: true })
    .filter((e) => e.isDirectory() && existsSync(join(THEMES, e.name, "palette.toml")))
    .map((e) => e.name)
    .sort();
}

// ── surfaces ────────────────────────────────────────────────────────────────
// A surface returns its name when it applied the theme, or null when the app
// isn't set up on this machine. Nothing here rewrites a whole config: rice
// owns theme files plus one pointer line, dovetail owns the rest.

const CONFIG = join(homedir(), ".config");

type Surface = { name: string; apply: (t: Theme) => string | null };

/** Swap the one line matching `re`. Hard-fails unless the match count is exactly 1. */
export function replaceLine(text: string, re: RegExp, line: string): string {
  const found = text.match(new RegExp(re.source, "gm"));
  if (found?.length !== 1)
    throw new Error(`expected 1 line matching ${re.source}, found ${found?.length ?? 0}`);
  // ponytail: function replacement so $& and friends in `line` stay literal.
  return text.replace(new RegExp(re.source, "m"), () => line);
}

const bare = (hex: string) => hex.slice(1);

/** A ghostty theme file: everything except `theme` and `config-file` is allowed. */
export function ghosttyTheme(t: Theme): string {
  return [
    `# ${t.meta.name} — generated by rice, do not edit`,
    `background = ${bare(t.roles.base)}`,
    `foreground = ${bare(t.roles.text)}`,
    `cursor-color = ${bare(t.roles.accent)}`,
    `cursor-text = ${bare(t.roles.on_fill)}`,
    `selection-background = ${bare(t.roles.overlay)}`,
    `selection-foreground = ${bare(t.ansi.white[1])}`,
    `background-opacity = ${t.render.opacity}`,
    ...ANSI.map((n, i) => `palette = ${i}=${t.ansi[n][0]}`),
    ...ANSI.map((n, i) => `palette = ${i + 8}=${t.ansi[n][1]}`),
    "",
  ].join("\n");
}

export const SURFACES: Surface[] = [
  {
    name: "ghostty",
    apply(t) {
      const dir = join(CONFIG, "ghostty");
      const cfg = join(dir, "config");
      if (!existsSync(cfg)) return null;
      mkdirSync(join(dir, "themes"), { recursive: true });
      writeFileSync(join(dir, "themes", t.slug), ghosttyTheme(t));
      writeFileSync(
        cfg,
        replaceLine(readFileSync(cfg, "utf8"), /^theme = .*$/, `theme = ${t.slug}`),
      );
      return "ghostty (supacode reads this config; p10k + fastfetch inherit its ANSI)";
    },
  },
];

const HELP = `rice — switch the whole desktop to a theme

usage:
  rice list              show available themes
  rice use <theme>       apply a theme to every surface
  rice -h, --help        this
`;

function main() {
  const [cmd, arg] = process.argv.slice(2);

  if (!cmd || cmd === "-h" || cmd === "--help") return console.log(HELP);

  if (cmd === "list") {
    for (const slug of listThemes()) {
      const t = loadTheme(slug);
      console.log(`${slug.padEnd(16)} ${t.meta.name} (${t.meta.variant}) — ${t.meta.description}`);
    }
    return;
  }

  if (cmd === "use") {
    if (!arg) throw new Error("usage: rice use <theme>");
    const t = loadTheme(arg);
    console.log(t.meta.name);
    for (const s of SURFACES) {
      const done = s.apply(t);
      console.log(done ? `  ✓ ${done}` : `  · ${s.name} not set up here, skipped`);
    }
    return;
  }

  throw new Error(`unknown command "${cmd}"\n\n${HELP}`);
}

if (import.meta.main) {
  try {
    main();
  } catch (e) {
    console.error(`rice: ${(e as Error).message}`);
    process.exit(1);
  }
}
